# Generated by ChatGPT
def split_string(text, n):
    return [text[i:i + n] for i in range(0, len(text), n)]


# Generated by ChatGPT
def split_list(lst, n):
    return [lst[i:i + n] for i in range(0, len(lst), n)]
